### ISSUE TITLE
Can't create Filter

### ISSUE THREAD

**Issue by squarepegsys** [thomst/django-admin-filter#9] opened 2021-02-01 01:04 UTC
So I followed the setup  -- I added it to INSTALLED_APPS, subclassed `AdminFilterSet` and added `CustomFilter` to the filter list.  And I see this in the Filter:
https://imgur.com/a/EwwKaLU
But when i click on New Filter, I get an error with:

`<model> with ID “filter” doesn’t exist. Perhaps it was deleted?`

So what did I do wrong?

**Comment by thomst** [comment] 2021-02-01 08:33
@squarepegsys Hi. Seems to be something wrong with the urlpath. It might be neccessary to include the django-admin-filter urls before the admin-urls:
```
urlpatterns = [
    path('admin/', include('django_admin_filter.urls')),
    path('admin/', admin.site.urls),
]
```

**Comment by squarepegsys** [comment] 2021-02-01 19:24
That is more or less what I was looking for.
but now the it returns the non-rendered HTML version of the page, i.e the actual HTML code:
https://imgur.com/a/F5Q0nVG

**Comment by thomst** [comment] 2021-03-08 17:49
@squarepegsys I have no idea why this is so and I cannot reproduce this error. Could you please:

- check your django-version and the compatibility with django_admin_filter
- post the full html-code which is returned by django_admin_filter
- check the content-type-response-header
- describe in detail when the issue occurs

Thanks

**Comment by pajusmar** [comment] 2021-04-13 15:37
> That is more or less what I was looking for.
> but now the it returns the non-rendered HTML version of the page, i.e the actual HTML code:
> https://imgur.com/a/F5Q0nVG

I was bumping into the same issue.

After renaming `self.content_type` on [this location](https://github.com/thomst/django-admin-filter/blob/cfb2f25338703d56485ac1996814e5ae43615b76/django_admin_filter/views.py#L56) (and relevant usages) new filters can be created again.

Version info below:

```
django-admin-filter==0.6
  - Django [required: >=2.2, installed: 3.2]
  - django-filter [required: >=2.2, installed: 2.4.0]
```

**Comment by thomst** [comment] 2021-06-23 09:33
This might be an issue with Dango 3.2. The app is only tested with django 2.2 to 3.1 and does not officially support django 3.2 yet. But this isn't reflected in the setup.py which uses "Django>=2.2" as requirenmet.

@pajusmar Would you mind to create a pull request or send me a diff with your changes?

**Comment by pajusmar** [comment] 2021-06-24 14:39
> This might be an issue with Dango 3.2. The app is only tested with django 2.2 to 3.1 and does not officially support django 3.2 yet. But this isn't reflected in the setup.py which uses "Django>=2.2" as requirenmet.
> 
> @pajusmar Would you mind to create a pull request or send me a diff with your changes?

Sure

**Comment by thomst** [comment] 2021-06-30 15:23
Thanks. I merged it and added official support for django 3.2 in version 0.7

**Closed as completed** 2021-06-30 15:23 UTC
